// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    created_at,
    updated_at,
    password
)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, email, created_at, updated_at, password, is_chirpy_red
`

type CreateUserParams struct {
	ID        uuid.UUID
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Password  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.IsChirpyRed,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :many
TRUNCATE TABLE users CASCADE
`

type DeleteUsersRow struct {
}

func (q *Queries) DeleteUsers(ctx context.Context) ([]DeleteUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, deleteUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteUsersRow
	for rows.Next() {
		var i DeleteUsersRow
		if err := rows.Scan(); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPassword = `-- name: GetUserPassword :one
SELECT id, email, created_at, updated_at, password, is_chirpy_red from users WHERE email = $1
`

func (q *Queries) GetUserPassword(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserPassword, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.IsChirpyRed,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET email = $2, updated_at = $4, password = $3 WHERE id = $1 RETURNING id, email, created_at, updated_at, password, is_chirpy_red
`

type UpdateUserParams struct {
	ID        uuid.UUID
	Email     string
	Password  string
	UpdatedAt sql.NullTime
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.IsChirpyRed,
	)
	return i, err
}

const upgradeToRed = `-- name: UpgradeToRed :exec
UPDATE users SET is_chirpy_red = TRUE WHERE id = $1
`

func (q *Queries) UpgradeToRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgradeToRed, id)
	return err
}
